//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/BRG/Projekte/RosMessageParser/RosMessageParser\RosMessage.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Joanneum.Robotics.Ros.MessageParser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRosMessageListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class RosMessageBaseListener : IRosMessageListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.ros_message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRos_message([NotNull] RosMessageParser.Ros_messageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.ros_message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRos_message([NotNull] RosMessageParser.Ros_messageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.ros_message_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRos_message_element([NotNull] RosMessageParser.Ros_message_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.ros_message_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRos_message_element([NotNull] RosMessageParser.Ros_message_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.field_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_declaration([NotNull] RosMessageParser.Field_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.field_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_declaration([NotNull] RosMessageParser.Field_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.constant_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant_declaration([NotNull] RosMessageParser.Constant_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.constant_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant_declaration([NotNull] RosMessageParser.Constant_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] RosMessageParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] RosMessageParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] RosMessageParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] RosMessageParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.header_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeader_type([NotNull] RosMessageParser.Header_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.header_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeader_type([NotNull] RosMessageParser.Header_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] RosMessageParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] RosMessageParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_type([NotNull] RosMessageParser.Array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_type([NotNull] RosMessageParser.Array_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.variable_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_array_type([NotNull] RosMessageParser.Variable_array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.variable_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_array_type([NotNull] RosMessageParser.Variable_array_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.fixed_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixed_array_type([NotNull] RosMessageParser.Fixed_array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.fixed_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixed_array_type([NotNull] RosMessageParser.Fixed_array_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.external_message_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternal_message_type([NotNull] RosMessageParser.External_message_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.external_message_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternal_message_type([NotNull] RosMessageParser.External_message_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.internal_message_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInternal_message_type([NotNull] RosMessageParser.Internal_message_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.internal_message_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInternal_message_type([NotNull] RosMessageParser.Internal_message_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.numeric_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumeric_type([NotNull] RosMessageParser.Numeric_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.numeric_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumeric_type([NotNull] RosMessageParser.Numeric_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.integral_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegral_type([NotNull] RosMessageParser.Integral_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.integral_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegral_type([NotNull] RosMessageParser.Integral_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.floating_point_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloating_point_type([NotNull] RosMessageParser.Floating_point_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.floating_point_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloating_point_type([NotNull] RosMessageParser.Floating_point_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.temportal_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemportal_type([NotNull] RosMessageParser.Temportal_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.temportal_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemportal_type([NotNull] RosMessageParser.Temportal_typeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Joanneum.Robotics.Ros.MessageParser
