//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/BRG/Projekte/RosMessageParser/RosMessageParser\RosMessage.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Joanneum.Robotics.Ros.MessageParser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RosMessageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IRosMessageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.ros_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRos_message([NotNull] RosMessageParser.Ros_messageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.ros_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRos_message([NotNull] RosMessageParser.Ros_messageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.ros_message_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRos_message_element([NotNull] RosMessageParser.Ros_message_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.ros_message_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRos_message_element([NotNull] RosMessageParser.Ros_message_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.field_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_declaration([NotNull] RosMessageParser.Field_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.field_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_declaration([NotNull] RosMessageParser.Field_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant_declaration([NotNull] RosMessageParser.Constant_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant_declaration([NotNull] RosMessageParser.Constant_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] RosMessageParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] RosMessageParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] RosMessageParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] RosMessageParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.header_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader_type([NotNull] RosMessageParser.Header_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.header_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader_type([NotNull] RosMessageParser.Header_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] RosMessageParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] RosMessageParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_type([NotNull] RosMessageParser.Array_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_type([NotNull] RosMessageParser.Array_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.variable_array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_array_type([NotNull] RosMessageParser.Variable_array_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.variable_array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_array_type([NotNull] RosMessageParser.Variable_array_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.fixed_array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixed_array_type([NotNull] RosMessageParser.Fixed_array_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.fixed_array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixed_array_type([NotNull] RosMessageParser.Fixed_array_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.external_message_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternal_message_type([NotNull] RosMessageParser.External_message_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.external_message_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternal_message_type([NotNull] RosMessageParser.External_message_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.internal_message_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInternal_message_type([NotNull] RosMessageParser.Internal_message_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.internal_message_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInternal_message_type([NotNull] RosMessageParser.Internal_message_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumeric_type([NotNull] RosMessageParser.Numeric_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumeric_type([NotNull] RosMessageParser.Numeric_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.integral_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegral_type([NotNull] RosMessageParser.Integral_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.integral_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegral_type([NotNull] RosMessageParser.Integral_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.floating_point_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloating_point_type([NotNull] RosMessageParser.Floating_point_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.floating_point_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloating_point_type([NotNull] RosMessageParser.Floating_point_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosMessageParser.temportal_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemportal_type([NotNull] RosMessageParser.Temportal_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosMessageParser.temportal_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemportal_type([NotNull] RosMessageParser.Temportal_typeContext context);
}
} // namespace Joanneum.Robotics.Ros.MessageParser
