//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/BRG/Projekte/RosMessageParser/Joanneum.Robotics.Ros.MessageParser\RosMessage.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Joanneum.Robotics.Ros.MessageParser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class RosMessageParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, BOOL=6, INT8=7, UINT8=8, INT16=9, 
		UINT16=10, INT32=11, UINT32=12, INT64=13, UINT64=14, FLOAT32=15, FLOAT64=16, 
		STRING=17, TIME=18, DURATION=19, ASSIGNMENT=20, SHARP=21, WHITESPACES=22, 
		NEWLINES=23, IDENTIFIER=24, INTEGER_LITERAL=25, REAL_LITERAL=26, REGULAR_STRING=27, 
		COMMENT=28;
	public const int
		RULE_ros_message = 0, RULE_ros_message_element = 1, RULE_field_declaration = 2, 
		RULE_constant_declaration = 3, RULE_comment = 4, RULE_identifier = 5, 
		RULE_header_type = 6, RULE_type = 7, RULE_array_type = 8, RULE_variable_array_type = 9, 
		RULE_fixed_array_type = 10, RULE_external_message_type = 11, RULE_internal_message_type = 12, 
		RULE_numeric_type = 13, RULE_integral_type = 14, RULE_floating_point_type = 15, 
		RULE_temportal_type = 16, RULE_string_type = 17, RULE_boolean_type = 18;
	public static readonly string[] ruleNames = {
		"ros_message", "ros_message_element", "field_declaration", "constant_declaration", 
		"comment", "identifier", "header_type", "type", "array_type", "variable_array_type", 
		"fixed_array_type", "external_message_type", "internal_message_type", 
		"numeric_type", "integral_type", "floating_point_type", "temportal_type", 
		"string_type", "boolean_type"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Header'", "'header'", "'['", "']'", "'/'", "'bool'", null, null, 
		"'int16'", "'uint16'", "'int32'", "'uint32'", "'int64'", "'uint64'", "'float32'", 
		"'float64'", "'string'", "'time'", "'duration'", "'='", "'#'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "BOOL", "INT8", "UINT8", "INT16", 
		"UINT16", "INT32", "UINT32", "INT64", "UINT64", "FLOAT32", "FLOAT64", 
		"STRING", "TIME", "DURATION", "ASSIGNMENT", "SHARP", "WHITESPACES", "NEWLINES", 
		"IDENTIFIER", "INTEGER_LITERAL", "REAL_LITERAL", "REGULAR_STRING", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RosMessage.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static RosMessageParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public RosMessageParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public RosMessageParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Ros_messageContext : ParserRuleContext {
		public Ros_message_elementContext[] ros_message_element() {
			return GetRuleContexts<Ros_message_elementContext>();
		}
		public Ros_message_elementContext ros_message_element(int i) {
			return GetRuleContext<Ros_message_elementContext>(i);
		}
		public ITerminalNode Eof() { return GetToken(RosMessageParser.Eof, 0); }
		public ITerminalNode[] NEWLINES() { return GetTokens(RosMessageParser.NEWLINES); }
		public ITerminalNode NEWLINES(int i) {
			return GetToken(RosMessageParser.NEWLINES, i);
		}
		public Ros_messageContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ros_message; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterRos_message(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitRos_message(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRos_message(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ros_messageContext ros_message() {
		Ros_messageContext _localctx = new Ros_messageContext(Context, State);
		EnterRule(_localctx, 0, RULE_ros_message);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38; ros_message_element();
			State = 43;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==NEWLINES) {
				{
				{
				State = 39; Match(NEWLINES);
				State = 40; ros_message_element();
				}
				}
				State = 45;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 46; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ros_message_elementContext : ParserRuleContext {
		public Field_declarationContext field_declaration() {
			return GetRuleContext<Field_declarationContext>(0);
		}
		public Constant_declarationContext constant_declaration() {
			return GetRuleContext<Constant_declarationContext>(0);
		}
		public CommentContext comment() {
			return GetRuleContext<CommentContext>(0);
		}
		public Ros_message_elementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ros_message_element; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterRos_message_element(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitRos_message_element(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRos_message_element(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ros_message_elementContext ros_message_element() {
		Ros_message_elementContext _localctx = new Ros_message_elementContext(Context, State);
		EnterRule(_localctx, 2, RULE_ros_message_element);
		try {
			State = 51;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 48; field_declaration();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 49; constant_declaration();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 50; comment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Field_declarationContext : ParserRuleContext {
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Array_typeContext array_type() {
			return GetRuleContext<Array_typeContext>(0);
		}
		public CommentContext comment() {
			return GetRuleContext<CommentContext>(0);
		}
		public Header_typeContext header_type() {
			return GetRuleContext<Header_typeContext>(0);
		}
		public Field_declarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field_declaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterField_declaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitField_declaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField_declaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Field_declarationContext field_declaration() {
		Field_declarationContext _localctx = new Field_declarationContext(Context, State);
		EnterRule(_localctx, 4, RULE_field_declaration);
		int _la;
		try {
			State = 65;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BOOL:
			case INT8:
			case UINT8:
			case INT16:
			case UINT16:
			case INT32:
			case UINT32:
			case INT64:
			case UINT64:
			case FLOAT32:
			case FLOAT64:
			case STRING:
			case TIME:
			case DURATION:
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 55;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
				case 1:
					{
					State = 53; type();
					}
					break;
				case 2:
					{
					State = 54; array_type();
					}
					break;
				}
				State = 57; identifier();
				State = 59;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMENT) {
					{
					State = 58; comment();
					}
				}

				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 2);
				{
				State = 61; header_type();
				State = 63;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMENT) {
					{
					State = 62; comment();
					}
				}

				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Constant_declarationContext : ParserRuleContext {
		public Integral_typeContext integral_type() {
			return GetRuleContext<Integral_typeContext>(0);
		}
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode ASSIGNMENT() { return GetToken(RosMessageParser.ASSIGNMENT, 0); }
		public ITerminalNode INTEGER_LITERAL() { return GetToken(RosMessageParser.INTEGER_LITERAL, 0); }
		public CommentContext comment() {
			return GetRuleContext<CommentContext>(0);
		}
		public Floating_point_typeContext floating_point_type() {
			return GetRuleContext<Floating_point_typeContext>(0);
		}
		public ITerminalNode REAL_LITERAL() { return GetToken(RosMessageParser.REAL_LITERAL, 0); }
		public ITerminalNode BOOL() { return GetToken(RosMessageParser.BOOL, 0); }
		public ITerminalNode STRING() { return GetToken(RosMessageParser.STRING, 0); }
		public ITerminalNode REGULAR_STRING() { return GetToken(RosMessageParser.REGULAR_STRING, 0); }
		public Constant_declarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant_declaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterConstant_declaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitConstant_declaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstant_declaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Constant_declarationContext constant_declaration() {
		Constant_declarationContext _localctx = new Constant_declarationContext(Context, State);
		EnterRule(_localctx, 6, RULE_constant_declaration);
		int _la;
		try {
			State = 99;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT8:
			case UINT8:
			case INT16:
			case UINT16:
			case INT32:
			case UINT32:
			case INT64:
			case UINT64:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 67; integral_type();
				State = 68; identifier();
				State = 69; Match(ASSIGNMENT);
				State = 70; Match(INTEGER_LITERAL);
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMENT) {
					{
					State = 72; comment();
					}
				}

				}
				break;
			case FLOAT32:
			case FLOAT64:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 75; floating_point_type();
				State = 76; identifier();
				State = 77; Match(ASSIGNMENT);
				State = 78;
				_la = TokenStream.LA(1);
				if ( !(_la==INTEGER_LITERAL || _la==REAL_LITERAL) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				State = 81;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMENT) {
					{
					State = 80; comment();
					}
				}

				}
				break;
			case BOOL:
				EnterOuterAlt(_localctx, 3);
				{
				{
				State = 83; Match(BOOL);
				State = 84; identifier();
				State = 85; Match(ASSIGNMENT);
				State = 86; Match(INTEGER_LITERAL);
				}
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMENT) {
					{
					State = 88; comment();
					}
				}

				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 4);
				{
				{
				State = 91; Match(STRING);
				State = 92; identifier();
				State = 93; Match(ASSIGNMENT);
				State = 94; Match(REGULAR_STRING);
				}
				State = 97;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMENT) {
					{
					State = 96; comment();
					}
				}

				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommentContext : ParserRuleContext {
		public ITerminalNode COMMENT() { return GetToken(RosMessageParser.COMMENT, 0); }
		public CommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterComment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitComment(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommentContext comment() {
		CommentContext _localctx = new CommentContext(Context, State);
		EnterRule(_localctx, 8, RULE_comment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101; Match(COMMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(RosMessageParser.IDENTIFIER, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 10, RULE_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Header_typeContext : ParserRuleContext {
		public Header_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_header_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterHeader_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitHeader_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHeader_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Header_typeContext header_type() {
		Header_typeContext _localctx = new Header_typeContext(Context, State);
		EnterRule(_localctx, 12, RULE_header_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105; Match(T__0);
			State = 106; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public Numeric_typeContext numeric_type() {
			return GetRuleContext<Numeric_typeContext>(0);
		}
		public Temportal_typeContext temportal_type() {
			return GetRuleContext<Temportal_typeContext>(0);
		}
		public Boolean_typeContext boolean_type() {
			return GetRuleContext<Boolean_typeContext>(0);
		}
		public String_typeContext string_type() {
			return GetRuleContext<String_typeContext>(0);
		}
		public External_message_typeContext external_message_type() {
			return GetRuleContext<External_message_typeContext>(0);
		}
		public Internal_message_typeContext internal_message_type() {
			return GetRuleContext<Internal_message_typeContext>(0);
		}
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 14, RULE_type);
		try {
			State = 114;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 108; numeric_type();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 109; temportal_type();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 110; boolean_type();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 111; string_type();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 112; external_message_type();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 113; internal_message_type();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Array_typeContext : ParserRuleContext {
		public Variable_array_typeContext variable_array_type() {
			return GetRuleContext<Variable_array_typeContext>(0);
		}
		public Fixed_array_typeContext fixed_array_type() {
			return GetRuleContext<Fixed_array_typeContext>(0);
		}
		public Array_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterArray_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitArray_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Array_typeContext array_type() {
		Array_typeContext _localctx = new Array_typeContext(Context, State);
		EnterRule(_localctx, 16, RULE_array_type);
		try {
			State = 118;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 116; variable_array_type();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 117; fixed_array_type();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_array_typeContext : ParserRuleContext {
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Variable_array_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_array_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterVariable_array_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitVariable_array_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_array_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_array_typeContext variable_array_type() {
		Variable_array_typeContext _localctx = new Variable_array_typeContext(Context, State);
		EnterRule(_localctx, 18, RULE_variable_array_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 120; type();
			State = 121; Match(T__2);
			State = 122; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Fixed_array_typeContext : ParserRuleContext {
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ITerminalNode INTEGER_LITERAL() { return GetToken(RosMessageParser.INTEGER_LITERAL, 0); }
		public Fixed_array_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fixed_array_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterFixed_array_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitFixed_array_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFixed_array_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Fixed_array_typeContext fixed_array_type() {
		Fixed_array_typeContext _localctx = new Fixed_array_typeContext(Context, State);
		EnterRule(_localctx, 20, RULE_fixed_array_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124; type();
			State = 125; Match(T__2);
			State = 126; Match(INTEGER_LITERAL);
			State = 127; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class External_message_typeContext : ParserRuleContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(RosMessageParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(RosMessageParser.IDENTIFIER, i);
		}
		public External_message_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_external_message_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterExternal_message_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitExternal_message_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExternal_message_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public External_message_typeContext external_message_type() {
		External_message_typeContext _localctx = new External_message_typeContext(Context, State);
		EnterRule(_localctx, 22, RULE_external_message_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129; Match(IDENTIFIER);
			State = 130; Match(T__4);
			State = 131; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Internal_message_typeContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(RosMessageParser.IDENTIFIER, 0); }
		public Internal_message_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_internal_message_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterInternal_message_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitInternal_message_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInternal_message_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Internal_message_typeContext internal_message_type() {
		Internal_message_typeContext _localctx = new Internal_message_typeContext(Context, State);
		EnterRule(_localctx, 24, RULE_internal_message_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Numeric_typeContext : ParserRuleContext {
		public Integral_typeContext integral_type() {
			return GetRuleContext<Integral_typeContext>(0);
		}
		public Floating_point_typeContext floating_point_type() {
			return GetRuleContext<Floating_point_typeContext>(0);
		}
		public Numeric_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numeric_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterNumeric_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitNumeric_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumeric_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Numeric_typeContext numeric_type() {
		Numeric_typeContext _localctx = new Numeric_typeContext(Context, State);
		EnterRule(_localctx, 26, RULE_numeric_type);
		try {
			State = 137;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT8:
			case UINT8:
			case INT16:
			case UINT16:
			case INT32:
			case UINT32:
			case INT64:
			case UINT64:
				EnterOuterAlt(_localctx, 1);
				{
				State = 135; integral_type();
				}
				break;
			case FLOAT32:
			case FLOAT64:
				EnterOuterAlt(_localctx, 2);
				{
				State = 136; floating_point_type();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Integral_typeContext : ParserRuleContext {
		public ITerminalNode INT8() { return GetToken(RosMessageParser.INT8, 0); }
		public ITerminalNode UINT8() { return GetToken(RosMessageParser.UINT8, 0); }
		public ITerminalNode INT16() { return GetToken(RosMessageParser.INT16, 0); }
		public ITerminalNode UINT16() { return GetToken(RosMessageParser.UINT16, 0); }
		public ITerminalNode INT32() { return GetToken(RosMessageParser.INT32, 0); }
		public ITerminalNode UINT32() { return GetToken(RosMessageParser.UINT32, 0); }
		public ITerminalNode INT64() { return GetToken(RosMessageParser.INT64, 0); }
		public ITerminalNode UINT64() { return GetToken(RosMessageParser.UINT64, 0); }
		public Integral_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_integral_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterIntegral_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitIntegral_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntegral_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Integral_typeContext integral_type() {
		Integral_typeContext _localctx = new Integral_typeContext(Context, State);
		EnterRule(_localctx, 28, RULE_integral_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INT8) | (1L << UINT8) | (1L << INT16) | (1L << UINT16) | (1L << INT32) | (1L << UINT32) | (1L << INT64) | (1L << UINT64))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Floating_point_typeContext : ParserRuleContext {
		public ITerminalNode FLOAT32() { return GetToken(RosMessageParser.FLOAT32, 0); }
		public ITerminalNode FLOAT64() { return GetToken(RosMessageParser.FLOAT64, 0); }
		public Floating_point_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_floating_point_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterFloating_point_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitFloating_point_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFloating_point_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Floating_point_typeContext floating_point_type() {
		Floating_point_typeContext _localctx = new Floating_point_typeContext(Context, State);
		EnterRule(_localctx, 30, RULE_floating_point_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141;
			_la = TokenStream.LA(1);
			if ( !(_la==FLOAT32 || _la==FLOAT64) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Temportal_typeContext : ParserRuleContext {
		public ITerminalNode TIME() { return GetToken(RosMessageParser.TIME, 0); }
		public ITerminalNode DURATION() { return GetToken(RosMessageParser.DURATION, 0); }
		public Temportal_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_temportal_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterTemportal_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitTemportal_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemportal_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Temportal_typeContext temportal_type() {
		Temportal_typeContext _localctx = new Temportal_typeContext(Context, State);
		EnterRule(_localctx, 32, RULE_temportal_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 143;
			_la = TokenStream.LA(1);
			if ( !(_la==TIME || _la==DURATION) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class String_typeContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(RosMessageParser.STRING, 0); }
		public String_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterString_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitString_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public String_typeContext string_type() {
		String_typeContext _localctx = new String_typeContext(Context, State);
		EnterRule(_localctx, 34, RULE_string_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Boolean_typeContext : ParserRuleContext {
		public ITerminalNode BOOL() { return GetToken(RosMessageParser.BOOL, 0); }
		public Boolean_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolean_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.EnterBoolean_type(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRosMessageListener typedListener = listener as IRosMessageListener;
			if (typedListener != null) typedListener.ExitBoolean_type(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRosMessageVisitor<TResult> typedVisitor = visitor as IRosMessageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolean_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Boolean_typeContext boolean_type() {
		Boolean_typeContext _localctx = new Boolean_typeContext(Context, State);
		EnterRule(_localctx, 36, RULE_boolean_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147; Match(BOOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1E', '\x98', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\a', '\x2', ',', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '/', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x5', '\x3', '\x36', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x5', '\x4', ':', '\n', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', 
		'>', '\n', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '\x42', '\n', 
		'\x4', '\x5', '\x4', '\x44', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 
		'L', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 'T', '\n', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x5', '\x5', '\\', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\x64', '\n', 
		'\x5', '\x5', '\x5', '\x66', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x5', '\t', 'u', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x5', '\n', 'y', 
		'\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x5', '\xF', '\x8C', '\n', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x2', '\x2', '\x15', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', 
		'&', '\x2', '\x6', '\x3', '\x2', '\x1B', '\x1C', '\x3', '\x2', '\t', '\x10', 
		'\x3', '\x2', '\x11', '\x12', '\x3', '\x2', '\x14', '\x15', '\x2', '\x99', 
		'\x2', '(', '\x3', '\x2', '\x2', '\x2', '\x4', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '\x43', '\x3', '\x2', '\x2', '\x2', '\b', '\x65', '\x3', 
		'\x2', '\x2', '\x2', '\n', 'g', '\x3', '\x2', '\x2', '\x2', '\f', 'i', 
		'\x3', '\x2', '\x2', '\x2', '\xE', 'k', '\x3', '\x2', '\x2', '\x2', '\x10', 
		't', '\x3', '\x2', '\x2', '\x2', '\x12', 'x', '\x3', '\x2', '\x2', '\x2', 
		'\x14', 'z', '\x3', '\x2', '\x2', '\x2', '\x16', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x18', '\x83', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x1E', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', ' ', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\"', '\x91', '\x3', '\x2', '\x2', '\x2', '$', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '&', '\x95', '\x3', '\x2', '\x2', '\x2', '(', '-', '\x5', 
		'\x4', '\x3', '\x2', ')', '*', '\a', '\x19', '\x2', '\x2', '*', ',', '\x5', 
		'\x4', '\x3', '\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', ',', '/', '\x3', 
		'\x2', '\x2', '\x2', '-', '+', '\x3', '\x2', '\x2', '\x2', '-', '.', '\x3', 
		'\x2', '\x2', '\x2', '.', '\x30', '\x3', '\x2', '\x2', '\x2', '/', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\a', '\x2', '\x2', '\x3', 
		'\x31', '\x3', '\x3', '\x2', '\x2', '\x2', '\x32', '\x36', '\x5', '\x6', 
		'\x4', '\x2', '\x33', '\x36', '\x5', '\b', '\x5', '\x2', '\x34', '\x36', 
		'\x5', '\n', '\x6', '\x2', '\x35', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x33', '\x3', '\x2', '\x2', '\x2', '\x35', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\x5', '\x3', '\x2', '\x2', '\x2', '\x37', ':', 
		'\x5', '\x10', '\t', '\x2', '\x38', ':', '\x5', '\x12', '\n', '\x2', '\x39', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x39', '\x38', '\x3', '\x2', '\x2', 
		'\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', ';', '=', '\x5', '\f', '\a', 
		'\x2', '<', '>', '\x5', '\n', '\x6', '\x2', '=', '<', '\x3', '\x2', '\x2', 
		'\x2', '=', '>', '\x3', '\x2', '\x2', '\x2', '>', '\x44', '\x3', '\x2', 
		'\x2', '\x2', '?', '\x41', '\x5', '\xE', '\b', '\x2', '@', '\x42', '\x5', 
		'\n', '\x6', '\x2', '\x41', '@', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x42', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x39', '\x3', '\x2', '\x2', '\x2', '\x43', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '\a', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', 
		'\x5', '\x1E', '\x10', '\x2', '\x46', 'G', '\x5', '\f', '\a', '\x2', 'G', 
		'H', '\a', '\x16', '\x2', '\x2', 'H', 'I', '\a', '\x1B', '\x2', '\x2', 
		'I', 'K', '\x3', '\x2', '\x2', '\x2', 'J', 'L', '\x5', '\n', '\x6', '\x2', 
		'K', 'J', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\x3', '\x2', '\x2', '\x2', 
		'L', '\x66', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\x5', ' ', '\x11', 
		'\x2', 'N', 'O', '\x5', '\f', '\a', '\x2', 'O', 'P', '\a', '\x16', '\x2', 
		'\x2', 'P', 'Q', '\t', '\x2', '\x2', '\x2', 'Q', 'S', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'T', '\x5', '\n', '\x6', '\x2', 'S', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', '\x66', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'V', '\a', '\b', '\x2', '\x2', 'V', 'W', '\x5', '\f', 
		'\a', '\x2', 'W', 'X', '\a', '\x16', '\x2', '\x2', 'X', 'Y', '\a', '\x1B', 
		'\x2', '\x2', 'Y', '[', '\x3', '\x2', '\x2', '\x2', 'Z', '\\', '\x5', 
		'\n', '\x6', '\x2', '[', 'Z', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\x3', 
		'\x2', '\x2', '\x2', '\\', '\x66', '\x3', '\x2', '\x2', '\x2', ']', '^', 
		'\a', '\x13', '\x2', '\x2', '^', '_', '\x5', '\f', '\a', '\x2', '_', '`', 
		'\a', '\x16', '\x2', '\x2', '`', '\x61', '\a', '\x1D', '\x2', '\x2', '\x61', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x62', '\x64', '\x5', '\n', '\x6', 
		'\x2', '\x63', '\x62', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x66', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x65', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x65', 'U', '\x3', '\x2', '\x2', '\x2', '\x65', ']', '\x3', '\x2', 
		'\x2', '\x2', '\x66', '\t', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 
		'\x1E', '\x2', '\x2', 'h', '\v', '\x3', '\x2', '\x2', '\x2', 'i', 'j', 
		'\a', '\x1A', '\x2', '\x2', 'j', '\r', '\x3', '\x2', '\x2', '\x2', 'k', 
		'l', '\a', '\x3', '\x2', '\x2', 'l', 'm', '\a', '\x4', '\x2', '\x2', 'm', 
		'\xF', '\x3', '\x2', '\x2', '\x2', 'n', 'u', '\x5', '\x1C', '\xF', '\x2', 
		'o', 'u', '\x5', '\"', '\x12', '\x2', 'p', 'u', '\x5', '&', '\x14', '\x2', 
		'q', 'u', '\x5', '$', '\x13', '\x2', 'r', 'u', '\x5', '\x18', '\r', '\x2', 
		's', 'u', '\x5', '\x1A', '\xE', '\x2', 't', 'n', '\x3', '\x2', '\x2', 
		'\x2', 't', 'o', '\x3', '\x2', '\x2', '\x2', 't', 'p', '\x3', '\x2', '\x2', 
		'\x2', 't', 'q', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', 
		'\x2', 't', 's', '\x3', '\x2', '\x2', '\x2', 'u', '\x11', '\x3', '\x2', 
		'\x2', '\x2', 'v', 'y', '\x5', '\x14', '\v', '\x2', 'w', 'y', '\x5', '\x16', 
		'\f', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 'x', 'w', '\x3', '\x2', 
		'\x2', '\x2', 'y', '\x13', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x5', 
		'\x10', '\t', '\x2', '{', '|', '\a', '\x5', '\x2', '\x2', '|', '}', '\a', 
		'\x6', '\x2', '\x2', '}', '\x15', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', 
		'\x5', '\x10', '\t', '\x2', '\x7F', '\x80', '\a', '\x5', '\x2', '\x2', 
		'\x80', '\x81', '\a', '\x1B', '\x2', '\x2', '\x81', '\x82', '\a', '\x6', 
		'\x2', '\x2', '\x82', '\x17', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', 
		'\a', '\x1A', '\x2', '\x2', '\x84', '\x85', '\a', '\a', '\x2', '\x2', 
		'\x85', '\x86', '\a', '\x1A', '\x2', '\x2', '\x86', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x88', '\a', '\x1A', '\x2', '\x2', '\x88', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x89', '\x8C', '\x5', '\x1E', '\x10', '\x2', 
		'\x8A', '\x8C', '\x5', ' ', '\x11', '\x2', '\x8B', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\t', '\x3', '\x2', '\x2', 
		'\x8E', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\t', '\x4', 
		'\x2', '\x2', '\x90', '!', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', 
		'\t', '\x5', '\x2', '\x2', '\x92', '#', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x94', '\a', '\x13', '\x2', '\x2', '\x94', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\a', '\b', '\x2', '\x2', '\x96', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x10', '-', '\x35', '\x39', '=', '\x41', '\x43', 
		'K', 'S', '[', '\x63', '\x65', 't', 'x', '\x8B',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Joanneum.Robotics.Ros.MessageParser
