image: microsoft/dotnet:latest

stages:
  - publish
  - build
  - test

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"
  tags:
    - docker-executor

test:
  stage: test
  script:
    - "dotnet test /p:CollectCoverage=true /p:Exclude=\"[xunit*]*\""
  tags:
    - docker-executor

test-output:
  stage: publish
  script: 
    - echo $CI_JOB_STAGE
    - echo $CI_PIPELINE_IID
    - echo $CI_PIPELINE_ID

nuget-pack:
  stage: publish
  script:
    - cd Joanneum.Robotics.Ros.MessageParser
    - dotnet pack -c Release -o bin/nuget --version-suffix $CI_PIPELINE_IID
  artifacts:
    paths:
      - bin/nuget/*
  tags:
    - docker-executor