image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"
  tags:
    - docker-executor

test:
  stage: test
  script:
    - "dotnet test /p:CollectCoverage=true /p:Exclude=\"[xunit*]*\""
  tags:
    - docker-executor

nuget-pack:
  stage: build
  script:
    - cd Joanneum.Robotics.Ros.MessageParser
    - dotnet pack -c Release -o bin/nuget --version-suffix $CI_PIPELINE_IID
  artifacts:
    paths:
      - bin/nuget/*
  tags:
    - docker-executor